### ISSUE TITLE
Remote connection

### ISSUE THREAD

**Issue by tomswinkels** [WebProject-xyz/ikea-tradfri-php#16]
Is it possible to make a remote connection by means of a port forward to port 5684?

**Comment by Fahl-Design** [comment]
Hi, yeah should be possible if you set up a port forward to map your external port to the not changeable port on the hub. I never tried to use it external since i don't want anybody use send request to network expect me ;) and I kind of hope that the hub only listens to local addresses

**Comment by tomswinkels** [comment]
I have try this.

- Port forward to the port 5684
- Run /ikea-tradfri-php-develop/wiki/example/example-list-lights.php

When i run that script i get a 504 Gateway Time-out.

**Comment by Fahl-Design** [comment]
hm ok, 
can you control the lights without the php part? just with the "plain" coap-client command? 
-- https://github.com/hvanderlaan/ikea-smartlight#requirements

i will check this php wrapper tomorrow or maybe later today, haven't used it in a while, maybe there was an update breaking it

**Comment by tomswinkels** [comment]
I have try that.

- RUN

`coap-client -m post -u "Client_identity" -k "<key>" -e '{"9090":"TOM"}' "coaps://<remoteip>:5684/15011/9063"`

- RESPONSE

```
v:1 t:CON c:POST i:4124 {} [ ]
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 50 bytes cleartext
{"9091":"<key>","9029":"1.4.0015"}
```

- NEXT RUN

`coap-client -m get -u "TOM" -k "<key>" "coaps://<remoteip>:5684/15001
`
- RESPONSE

```
v:1 t:CON c:GET i:52e6 {} [ ]
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 78 bytes cleartext
[65546,65538,65536,65539,65542,65543,65545,65540,65541,65544,65537]
```

**Comment by Fahl-Design** [comment]
Ok great. This looks good and I ran into the same timeout error as you, because my username was no longer set up on the hub

To fix it: 

Go to your `wiki/example/init.php` and change "php-api-user" to "TOM" 
`$commands = new Coaps(COAP_GATEWAY_IP, COAP_GATEWAY_SECRET, COAP_API_KEY, 'TOM');` 

![image](https://user-images.githubusercontent.com/6690962/50422894-0e7ca880-084f-11e9-890b-ccaeb5e5d88a.png)

or create a new API user with the name of "php-api-user" (but this doesn't matter anyway if in your case) 

![image](https://user-images.githubusercontent.com/6690962/50422885-ec832600-084e-11e9-9c39-755d46a76efb.png)

**Comment by tomswinkels** [comment]
Thanks, that works.

What i have do:

RUN

`coap-client -m post -u "Client_identity" -k "<secret>" -e '{"9090":"php-api-user"}' "coaps://<remoteip>:5684/15011/9063"`

RESPONSE

```
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 50 bytes cleartext
{"9091":"<apikey>","9029":"1.4.0015"}
```

CHANGE INIT.php

```
define('COAP_GATEWAY_IP', 'remoteip');
define('COAP_GATEWAY_SECRET', 'secret');
define('COAP_API_KEY', 'apikey');
```
