### ISSUE TITLE
Question: Events

### ISSUE THREAD

**Issue by tomswinkels** [WebProject-xyz/ikea-tradfri-php#20]
I have a Ikea sensor.

When the sensor sees an activity, does an event start in the hub?

Do I have to leave a connection open to the hub that is listening to everything that happens? (maybe there is an example)

**Comment by Fahl-Design** [comment]
I'm not quite sure if there is a network event for this.
in any way this php api wrapper can't handle network events because it only sends api commands to the hub in order to get information or change light states etc

But I found https://github.com/tzolov/coap-shell and it looks nice to control the hub and see even more information

**Comment by tomswinkels** [comment]
Thnx.

I go try if i can make something!

**Comment by Fahl-Design** [comment]
maybe this can help you:
https://github.com/obgm/libcoap/issues/196
